// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoLcGR14GDer8bzOEIv7ZBqGdFC4y7nWw',
    appId: '1:483327660130:web:4d29c1c141d9b64ac7413b',
    messagingSenderId: '483327660130',
    projectId: 'fota-3324f',
    authDomain: 'fota-3324f.firebaseapp.com',
    databaseURL: 'https://fota-3324f-default-rtdb.firebaseio.com',
    storageBucket: 'fota-3324f.appspot.com',
    measurementId: 'G-6X628BTNXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO1TTtL7X9gvTQ-7xTQOmpBqiMXMjfnqw',
    appId: '1:483327660130:android:abee9881860d8858c7413b',
    messagingSenderId: '483327660130',
    projectId: 'fota-3324f',
    databaseURL: 'https://fota-3324f-default-rtdb.firebaseio.com',
    storageBucket: 'fota-3324f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_39ayjZu4enahvrH4ycx8e_On9YBmCc',
    appId: '1:483327660130:ios:ac6db0dd86d73f04c7413b',
    messagingSenderId: '483327660130',
    projectId: 'fota-3324f',
    databaseURL: 'https://fota-3324f-default-rtdb.firebaseio.com',
    storageBucket: 'fota-3324f.appspot.com',
    iosBundleId: 'com.example.fota',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_39ayjZu4enahvrH4ycx8e_On9YBmCc',
    appId: '1:483327660130:ios:ac6db0dd86d73f04c7413b',
    messagingSenderId: '483327660130',
    projectId: 'fota-3324f',
    databaseURL: 'https://fota-3324f-default-rtdb.firebaseio.com',
    storageBucket: 'fota-3324f.appspot.com',
    iosBundleId: 'com.example.fota',
  );
}
