/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Inc/Services/COMM/COMM_Interface.h"
#include "../Inc/Services/SYSCLOCK/SYSCLOCK.h"
void SystemClock_Config(void);

COM_SESSION session_1 =
{
		.SessionID = 1,
		.Session_Protocol = SESSION_UART,
		.SessionMODE = SESSION_NormalMODE,
		.pSessionHandler = &Huart1
};

int main(void)
{
	SystemClock_Config();
    COMM_SessionInit(&session_1);
	for(;;);
}
